excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Hhalvi.github.io
title: Harsha Halvi
email: harsha@hhalvi.in
author: Harsha Halvi
description: Blog of Harsha Halvi
paginate: 6
google_analytics: 